name: Test CI

on: pull_request

jobs:
  test-ci:
    name: Test CI
    runs-on: ubuntu-latest

    steps:
      - name: Test URL
        uses: envoy/check-url-action@main
        with:
          url: https://abcd.com/
